version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: bundle install
      - run: git clone git@github.com:rocky-mountain-institute/gtfs-best-practices.git _best-practices/
      - run: git clone git@github.com:rocky-mountain-institute/gtfs-reference.git _reference/
      - run: bundle exec jekyll build
      - deploy:
        - name: Deploy to S3
        - command: aws s3 sync _site s3://alexperez.ninja/ --delete


