version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Clone document repos
          command: git clone git@github.com:itd-consortium/gtfs-best-practices.git _best-practices/
          command: git clone git@github.com:itd-consortium/gtfs-reference.git _reference/
      - run: bundle exec jekyll build
      - deploy:
          name: Deploy to S3
          command: aws s3 sync _site s3://alexperez.ninja/ --delete


