machine:
  environment:
    NOKOGIRI_USE_SYSTEM_LIBRARIES: true # speeds up installation of html-proofer

dependencies:
  post:
    - git clone git@github.com:rocky-mountain-institute/gtfs-best-practices.git _best-practices/
    - git clone git@github.com:rocky-mountain-institute/gtfs-reference.git _reference/

test:
  post:
    # - bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external
      - bundle exec jekyll build

deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync _site s3://gtfs.org/ --delete
